import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { relative, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const root = fileURLToPath(new URL('../', import.meta.url));
function files(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap(e =>
    e.isDirectory() ? (e.name === 'generated' ? [] : files(join(dir, e.name))) : [join(dir, e.name)]);
}
const inputs = [...files(join(root, 'src')), ...files(join(root, 'spec')),
  join(root, 'scripts/build.mjs'), join(root, 'package.json'), join(root, 'package-lock.json'), join(root, 'tsconfig.json')].sort();
const hash = createHash('sha256');
for (const path of inputs) hash.update(JSON.stringify([relative(root, path).replaceAll('\\', '/'), readFileSync(path, 'utf8')]));
const digest = hash.digest('hex');
mkdirSync(join(root, 'src/generated'), { recursive: true });
writeFileSync(join(root, 'src/generated/build-info.ts'),
  `// Generated by scripts/build.mjs; do not edit.\nexport const ENGINE_DIGEST = ${JSON.stringify(digest)};\nexport const ENGINE_VERSION = '0.1.0';\n`);
const result = spawnSync(process.execPath, [resolve(root, 'node_modules/typescript/bin/tsc'), '-p', resolve(root, 'tsconfig.json')], { stdio: 'inherit', cwd: root });
if (result.error) { console.error(result.error.message); process.exit(1); }
process.exit(result.status ?? 1);
